controllers/AddressController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use app\models\Address;
use app\models\AddressSearch;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\base\Widget;
/**
 * AddressController implements the CRUD actions for Address model.
 */
class AddressController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
//                        'actions'=>['index'],
                        'allow' => true,
                        'roles' => ['@'],
//                        'matchCallback' => function($rule, $action){
//                            return Yii::$app->user->identity->role_id == User::ROLE_ADMIN;
//                        },
                    ],
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ]
                ],
            ]
        ];
    }

    /**
     * Lists all Address models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AddressSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Address model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Address model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Address();
        $client_id = Yii::$app->request->get('id');
        if (Yii::$app->request->isAjax)
        {
            $data = Yii::$app->request->post();
            if ($model->load($data) && $model->validate())
            {
                $model->client_id = $client_id;
                //$returnUrl = Url::toRoute(['client/view']);
                if ($model->save())
                    return
                        Yii::$app->runAction('client/view', ['id' => $model->client_id]);
                        //'redirect'=> Url::toRoute('/client/view', ['id' => $model->client_id])

            }
            else
            {
                $x = $model->getErrors();
                return $this->renderAjax('create', [
                    'model' => $model,
                ]);
            }
        }
        if ($model->load(Yii::$app->request->post())) {
            $model->client_id = $client_id;
            if ($model->validate() && $model->save()) {
                $urlBack = Url::toRoute(['client/view', 'id' => $model->client_id]);
                return $this->redirect($urlBack);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Address model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (Yii::$app->request->isAjax)
            {
                return Yii::$app->runAction('client/view', ['id' => $model->client_id]);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            if (Yii::$app->request->isAjax)
                return $this->renderAjax('update', [
                    'model' => $model,
                ]);
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Address model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->delete();

        if (Yii::$app->request->isAjax)
            return Yii::$app->runAction('/client/view', ['id' => $model->client_id]);
        $urlBack = Url::toRoute(['/client/view', 'id' => $model->client_id]);
        return $this->redirect($urlBack);
    }

    /**
     * Finds the Address model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Address the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Address::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/address/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use demogorgorn\ajax\AjaxSubmitButton;
/* @var $this yii\web\View */
/* @var $model app\models\Address */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="address-form">

    <?php $form = ActiveForm::begin(['options' => ['data-pjax' => true],'id' => 'wx']); ?>
<!---->
<!--    --><?//= $form->field($model, 'client_id')->textInput() ?>

<!--    --><?//= $form->field($model, 'client_id')->textInput() ?>
    <?= $form->field($model, 'town')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'street')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'house')->textInput() ?>
    <?= $form->field($model, 'flat')->textInput() ?>
    <?= $form->field($model, 'porch')->textInput() ?>
    <?= $form->field($model, 'organisation_name')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'comment')->textarea(['rows' => 6, 'maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
<!--        --><?//
//        AjaxSubmitButton::begin([
//            'label' => 'Сохранить',
//            'ajaxOptions' => [
//                'type' => 'POST',
//                'url' => \yii\helpers\Url::toRoute('/address/create'),
//                'success' => new \yii\web\JsExpression('function(responseText){
//                        $("#container").empty();
//                        $("#container").append(responseText);
//                    }'),
//            ],
//            'options' => ['id' => 'wx', 'class' => 'btn btn-success', 'type' => 'submit'],
//        ]);
//        AjaxSubmitButton::end();
//        ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/address/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AddressSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="address-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'client_id') ?>

    <?= $form->field($model, 'town') ?>

    <?= $form->field($model, 'street') ?>

    <?= $form->field($model, 'house') ?>

    <?php // echo $form->field($model, 'flat') ?>

    <?php // echo $form->field($model, 'porch') ?>

    <?php // echo $form->field($model, 'organisation_name') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/address/create.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

/* @var $this yii\web\View */
/* @var $model app\models\Address */
$client = \app\models\Client::findOne(['id' => Yii::$app->request->get('id')]);
$this->title = Yii::t('app', 'Create {modelClass}: ', [
        'modelClass' => 'Address',
    ]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Clients'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $client->name, 'url' => ['client/view', 'id' => $client->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Create {modelClass}: ', [
    'modelClass' => 'Address',
]);

if (Yii::$app->request->isAjax)
    echo Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]); ?>
<div class="address-create">
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/address/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Addresses';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="address-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Address', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <? $this->render('_search', [
        'model' => $searchModel
    ])?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'client_id',
            'town',
            'street',
            'house',
            // 'flat',
            // 'porch',
            // 'organisation_name',
            // 'comment',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/address/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Address */
use yii\widgets\Breadcrumbs;
$client = $model->getClient()->one();
$this->title = Yii::t('app', 'Update Address');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Clients'), 'url' => ['/client/index']];
$this->params['breadcrumbs'][] = ['label' => $client->name, 'url' => ['client/view', 'id' => $model->client_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');

if (Yii::$app->request->isAjax)
    echo Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]);
?>
<div class="address-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/address/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Address */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Addresses', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="address-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'client_id',
            'town',
            'street',
            'house',
            'flat',
            'porch',
            'organisation_name',
            'comment',
        ],
    ]) ?>

</div>